### PR TITLE
Panning

### PR DESCRIPTION
**Pull request by c3r1c3**
2 things:
1.  A test of me trying to issue a PR to someone else's (non-merged) branch.
2. This is code that allows for panning even when OBS is set to output in mono mode and future-proofs OBS for multi-channel output.

Please don't merge this as is, I still have a bit to do, but hopefully this is a start.

### CODE REVIEW

**Comment by c3r1c3** [comment]
Okay, so my next thought is that when the downmix to mono option is checked it shouldn't output to both channels, but to only 1, and that one channel is controlled by the panner.

**Comment by c3r1c3** [comment]
Okay, fixed the above.

Now on to setting up the pan setting to record/pass along/calculate the panning per channel. (And then configure the interface to do all the fun stuff we want).

**Comment by c3r1c3** [comment]
Yes even more changes, but still not building/done.

**Comment by c3r1c3** [comment]
Making progress, but a bit stuck on how to store and retrieve an array for saving state. If I can get past that (and the correct accessor functions) I can do the interface and finish the panning math.

**Comment by cg2121** [comment]
Maybe you could implement your per channel panning code as a filter, so no backend code is changed.

**Comment by c3r1c3** [comment]
I'll do that. If you want to grab anything I've done and edit it into your PR go for it.

Note: I'm not sure what to do at this point. Do I close this PR?

**Comment by cg2121** [comment]
IMO, it would be better to close this PR and issue one to the main repo when you are done.

**Pull request closed without merging**
